runtime: nodejs20
env_variables:
  NODE_ENV: $NODE_ENV
  INFISICAL_CLIENT_ID: $INFISICAL_CLIENT_ID
  INFISICAL_CLIENT_SECRET: $INFISICAL_CLIENT_SECRET
  INFISICAL_PROJECT_ID: $INFISICAL_PROJECT_ID
build_env_variables:
  ENV: $NODE_ENV
  INFISICAL_CLIENT_ID: $INFISICAL_CLIENT_ID
  INFISICAL_CLIENT_SECRET: $INFISICAL_CLIENT_SECRET
  INFISICAL_PROJECT_ID: $INFISICAL_PROJECT_ID
