name: Xata migrate dev to main

on:
  workflow_dispatch:

jobs:
  migrate_dev_to_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Load Secrets in Env
        run: |
          npx tsx ./scripts/load-secrets-ci
        env:
          NODE_ENV: dev
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          INFISICAL_PROJECT_ID: ${{ secrets.INFISICAL_PROJECT_ID }}

      - name: Install Xata CLI
        run: |
          npm install -g @xata.io/cli@latest

      - name: Migrate DB schema from dev to main
        run: |
          npx tsx ./scripts/xata-migration dev main
        env:
          FORCE: true
